<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KabanCalculator</AssemblyName>
    <RootNamespace>KabanCalculator</RootNamespace>
    <ApplicationIcon>Assets\kabancalculator.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Assets\default-library.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Resource Include="Assets\kabancalculator.ico" />
  </ItemGroup>
</Project>